package zm.co.codelabs.adm.engine.model;

public enum ErrorCode {
    NETWORK_TRANSIENT, DNS, TLS, AUTH_REQUIRED, HTTP_CLIENT_FATAL, HTTP_SERVER_TRANSIENT,
    RANGE_UNSUPPORTED, RESOURCE_CHANGED, DISK_FULL, PERMISSION, FILESYSTEM,
    CHECKSUM_MISMATCH, USER_CANCELED, NONE
}
